### ISSUE TITLE
Improve `package-operator-manager` log messages

### ISSUE THREAD

**Issue by jan--f** [package-operator/package-operator#100]
I created a malformed package and am a very new user. I tried to get information from the package-operator-manager and indeed found an error. However the message was not very helpful. Maybe this can be improved?
Seems like the right way is to look at the status of the respective `[Cluster]Package`. Even such a hint from the manager would be helpful I think.

Log message:
```
1.6697180513561141e+09	ERROR	Reconciler error	{"controller": "clusterpackage", "controllerGroup": "package-operator.run", "controllerKind": "ClusterPackage", "ClusterPackage": {"name":"example"}, "namespace": "", "name": "example", "reconcileID": "b4c62ea1-cf43-4ce5-9eaf-39c553e3ae00", "error": "Operation cannot be fulfilled on clusterpackages.package-operator.run \"example\": StorageError: invalid object, Code: 4, Key: /registry/package-operator.run/clusterpackages/example, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 7dda66fb-4650-48c0-90ca-b54652b74ada, UID in object meta: "}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234
```

**Comment by thetechnick** [comment]
Hi @jan--f !
Improving UX and error reporting is top of the list :)
We are tracking most of that work in RH-internal Jira:
e.g. https://issues.redhat.com/browse/MTSRE-788

Internal refactoring to improve is already merged:
https://github.com/package-operator/package-operator/pull/97

We are also working on streamlining the package build process and validation via a new CLI.
Soon you will be able to get a lot of information before even deploying to a cluster:
```
$ kubectl package validate ./my-package-directory
Package validation errors:
- Missing package-operator.run/phase Annotation in my-deployment.yaml#0
```

**Comment by thetechnick** [comment]
closing as stale.
A lot has happened over the last months.
Please reopen if the issue persists.
