### ISSUE TITLE
BUG: mage deploy tries to deploy nonexistent tag of package-operator-manager

### ISSUE THREAD

**Issue by bentito** [package-operator/package-operator#81]
I typed:
```bash
./mage deploy
```
expected Package Operator to deploy to my kind cluster.

But it timed out due to pull attempt on a tag that does not exist:

It tried to pull:

`quay.io/package-operator/package-operator-manager:f3f48ec`

But the quay.io list of tags currently looks like this:
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/4449199/200406574-9bce0436-071f-4973-9cd4-dbf37d5ce6fc.png">

**Comment by bentito** [comment]
Ah I see why this happens...
https://github.com/package-operator/package-operator/blob/main/magefile.go#L292
This results in the behavior I am seeing. This doesn't seem like a good behavior though. Would it be better to do a `os.LookupEnv("VERSION")` and if not defined, stop with an appropriate error message, rather than put this commit ID that won't exist in the default (quay.io) registry?

**Comment by thetechnick** [comment]
Hi @bentito, thanks for opening this ticket!

The command: `./mage dev:deploy` Notice the `dev:`! will create a new kind cluster and deploy PKO on top.
We are using this every day, so we know it's working on Fedora + podman and OSX + docker :)

You will also find multiple install modes documented here:
https://package-operator.run/docs/getting_started/installation/

If you don't want to develop, but just try out PKO, I would recommend to use the self-boostrap-job on a kind cluster:
`kubectl create -f https://github.com/package-operator/package-operator/releases/latest/download/self-bootstrap-job.yaml`

**Comment by bentito** [comment]
👍

**Comment by eqrx** [comment]
Hey all, is this issue resolved and can it be closed?:)

**Comment by bentito** [comment]
Seems like it, closing.
